name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  client-tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: ./gradlew allTests
